name: CI pipeline

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}
    - name: install uv and dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        uv sync
    
    - name: linting + formatting checks
      run: |
        uv run black . -l 79